FROM python:3.11-slim

ADD https://github.com/THUDM/CogVLM/raw/main/openai_demo/openai_api.py /usr/src/
WORKDIR /usr/src

# reduced dependencies for smaller image size
RUN pip install --no-cache-dir transformers>=4.36.2 torch>=2.1.0 torchvision>=0.16.2 pydantic>=2.6.0 fastapi>=0.109.0 uvicorn>=0.27.0 loguru~=0.7.2 sse-starlette>=1.8.2 \
	xformers>=0.0.22 accelerate>=0.26.1 pillow>=10.2.0 timm>=0.9.12 einops sentencepiece protobuf bitsandbytes 

CMD python openai_api.py
