FROM python:3.11-slim

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/01-ai/Yi /app
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir loguru openai sse-starlette tiktoken

CMD python VL/openai_api.py
